### ISSUE TITLE
Port your code from old repository

### ISSUE THREAD

**Issue by acarteas** [abbottjord94/CS211-TextEditor#1]
It doesn't look like much is in here.  Why didn't you bring everything over from the old repository?  I looked at your old repo.  Opening a file should be optional.  Loading file doesn't put text in correct location.

**Comment by abbottjord94** [comment]
Most of the functions have been reimplemented as of https://github.com/abbottjord94/CS211-TextEditor/commit/ad99e11e47acc6158938518960d3905b16fa4916
